# Generated by Django 5.1.7 on 2025-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_isbn_alter_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
    ]
